[package]
name = "pancakellm"
version = "0.1.0"
edition = "2021"

[dependencies]
tch = "0.10.1"
tokenizers = "0.13.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5"
ndarray = "0.15"
anyhow = "1.0"

[features]
cuda = ["tch/cuda"]
