name: Integration

on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_check:
    name: Rust build and checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install libtorch
        run: |
          pip install torch

      - name: Format
        run: cargo fmt -- --check

      # - name: Linter
      #   run: cargo clippy -- -D warnings

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
